#分成database、other两部分，其下各字段都可以自定义
database:
  mysql:
    host: "127.0.0.1"
    port: "3306"
    username: "root"
    password: "password"

  redis:
    host: "127.0.0.1"
    port: "6379"
    username: "root"
    passowrd: "password"
    db: 0

other:
  grpc:
    address: "50051"